package generated_audio

// =====================================================================
// Generated by Skald.
//
// SFX assets: (none)
// Music Layer assets: GW_Hat_Static GW_Grunt_Swarm_Bass GW_Splitter_Echo_Stab Tuba Growly_Sax
//
// Game integration: import this package and use the per-asset APIs.
//   SFX:         <Foo>_init, <Foo>_trigger, <Foo>_process, <Foo>_is_playing
//   Music Layer: <Bar>_init, <Bar>_start, <Bar>_stop, <Bar>_process,
//                <Bar>_set_loop
//
// <Foo>_trigger with duration<=0 (the default) plays a natural one-shot:
// the envelope holds through attack+decay, then releases (a patch with no
// envelope plays 1s). Pass an explicit duration in seconds to hold longer,
// or drive <Foo>_note_on / <Foo>_note_off yourself for full control.
//
// project_init/process/destroy is a convenience wrapper for the test
// harness only — game code should consume per-asset procs directly.
// =====================================================================

import "core:math"
import "core:math/rand"

PRNG_State :: struct {
	state: u32,
}

next_float32 :: proc(rng: ^PRNG_State) -> f32 {
	x := rng.state
	x ~= x << 13
	x ~= x >> 17
	x ~= x << 5
	if x == 0 do x = 0xDEADBEEF
	rng.state = x
	return f32(x) / 4294967296.0
}

ADSR_Stage :: enum { Idle, Attack, Decay, Sustain, Release }

skald_wavetable_shape :: proc(idx: int, ph: f32) -> f32 {
	switch idx {
	case 1: return abs(ph * 4.0 - 2.0) - 1.0
	case 2: return ph * 2.0 - 1.0
	case 3: return ph < 0.5 ? 1.0 : -1.0
	}
	return math.sin(ph * 2.0 * f32(math.PI))
}

skald_wavetable_sample :: proc(ph: f32, pos: f32) -> f32 {
	p := math.clamp(pos, 0.0, 3.0)
	i1 := int(p)
	i2 := (i1 + 1) % 4
	frac := p - f32(i1)
	s1 := skald_wavetable_shape(i1, ph)
	s2 := skald_wavetable_shape(i2, ph)
	return s1 + (s2 - s1) * frac
}

Note_Event :: struct {
	note: u8,
	velocity: f32,
	start_time: f32,
	step: int,
	duration: f32,
}

Skald_Param_Info :: struct {
	name:    string,
	min:     f32,
	max:     f32,
	default: f32,
	unit:    string,
}

GW_Hat_Static_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	adsr_static_amp_stage: ADSR_Stage,
	adsr_static_amp_release_level: f32,
	filter_static_filter_low: f32,
	filter_static_filter_band: f32,
	noise_static_noise_rng: PRNG_State,
}

GW_Hat_Static_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [4]GW_Hat_Static_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	amplitude: f32,
	cutoff: f32,
	decay: f32,
}

GW_Hat_Static_init :: proc(p: ^GW_Hat_Static_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 145.000000000
	p.prng.state = 12345
	p.loop = true
	for i in 0..<4 {
		v := &p.voices[i]
		v.noise_static_noise_rng.state = u32(0xC0FFEE01) ~ u32(i + 1) * 2654435761
	}
	p.amplitude = 0.500000000
	p.cutoff = 7800.000000000
	p.decay = 0.045000002
}

GW_Hat_Static_note_on :: proc(p: ^GW_Hat_Static_Processor, note: u8, velocity: f32, duration: f32) {
	voice_idx := -1
	for i in 0..<4 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_age: f32 = -1.0
		for i in 0..<4 {
			if p.voices[i].age > oldest_age {
				oldest_age = p.voices[i].age
				voice_idx = i
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.000000000
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_static_amp_stage = .Attack
	v.adsr_static_amp_release_level = 0.0
	v.filter_static_filter_low = 0.0
	v.filter_static_filter_band = 0.0
}

GW_Hat_Static_note_off :: proc(p: ^GW_Hat_Static_Processor, note: u8) {
	best := -1
	best_age: f32 = -1.0
	for i in 0..<4 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_static_amp_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_static_amp_stage = .Release
	}
}

GW_Hat_Static_trigger :: proc(p: ^GW_Hat_Static_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (f32(0.001000000)) + (p.decay) > d do d = (f32(0.001000000)) + (p.decay)
		if d <= 0.0 do d = 0.001
	}
	GW_Hat_Static_note_on(p, note, velocity, d)
}

GW_Hat_Static_feed_input :: proc(p: ^GW_Hat_Static_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

GW_Hat_Static_start :: proc(p: ^GW_Hat_Static_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

GW_Hat_Static_stop :: proc(p: ^GW_Hat_Static_Processor) {
	p.playing = false
}

GW_Hat_Static_set_loop :: proc(p: ^GW_Hat_Static_Processor, loop: bool) {
	p.loop = loop
}

GW_Hat_Static_is_playing :: proc(p: ^GW_Hat_Static_Processor) -> bool {
	if p.playing do return true
	for i in 0..<4 {
		if p.voices[i].active do return true
	}
	return false
}

GW_Hat_Static_set_amplitude :: proc(p: ^GW_Hat_Static_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.amplitude = v
}

GW_Hat_Static_set_cutoff :: proc(p: ^GW_Hat_Static_Processor, value: f32) {
	v := value
	if v < 20.000000000 do v = 20.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.cutoff = v
}

GW_Hat_Static_set_decay :: proc(p: ^GW_Hat_Static_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.decay = v
}

GW_Hat_Static_PARAMS := []Skald_Param_Info{
	{"amplitude", 0.000000000, 1.000000000, 0.500000000, ""},
	{"cutoff", 20.000000000, 20000.000000000, 7800.000000000, "Hz"},
	{"decay", 0.001000000, 10.000000000, 0.045000002, "s"},
}

GW_Hat_Static_set_param :: proc(p: ^GW_Hat_Static_Processor, name: string, value: f32) -> bool {
	switch name {
	case "amplitude":
		GW_Hat_Static_set_amplitude(p, value)
		return true
	case "cutoff":
		GW_Hat_Static_set_cutoff(p, value)
		return true
	case "decay":
		GW_Hat_Static_set_decay(p, value)
		return true
	}
	return false
}

GW_Hat_Static_get_param :: proc(p: ^GW_Hat_Static_Processor, name: string) -> (f32, bool) {
	switch name {
	case "amplitude":
		return p.amplitude, true
	case "cutoff":
		return p.cutoff, true
	case "decay":
		return p.decay, true
	}
	return 0.0, false
}

GW_Hat_Static_process :: proc(p: ^GW_Hat_Static_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	GW_Hat_Static_process_sequence(p)
	p.total_samples += 1

	for v_idx in 0..<4 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_static_amp_stage != .Release && voice.adsr_static_amp_stage != .Idle {
				voice.adsr_static_amp_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_static_amp_out: f32 = 0.0
		node_static_filter_out: f32 = 0.0
		node_static_noise_out: f32 = 0.0
		node_static_output_out: f32 = 0.0

		// --- Noise Node static_noise ---
		node_static_noise_out = (next_float32(&voice.noise_static_noise_rng) * 2.0 - 1.0) * (p.amplitude);

		// --- Filter Node static_filter (SVF) ---
		{
			cutoff_c_static_filter: f32 = math.clamp(f32(p.cutoff), 10.0, sample_rate * 0.16);
			f_static_filter := f32(2.0 * math.sin(f32(math.PI) * cutoff_c_static_filter / sample_rate));
			q_static_filter: f32 = math.clamp(1.0 / math.max(f32(f32(1.100000000)), 0.1), 0.05, 1.9 - f_static_filter);
			voice.filter_static_filter_low += f_static_filter * voice.filter_static_filter_band;
			high_static_filter := f32(((node_static_noise_out)) - voice.filter_static_filter_low - q_static_filter * voice.filter_static_filter_band);
			voice.filter_static_filter_band += f_static_filter * high_static_filter;
			node_static_filter_out = voice.filter_static_filter_band;
		}

		// --- ADSR Node static_amp ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_static_amp_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (f32(0.001000000)) > 0 do envelope = voice.age / math.max(f32(f32(0.001000000)), 0.000001); else do envelope = 1.0;
				voice.adsr_static_amp_release_level = envelope;
				if voice.age >= (f32(0.001000000)) {
					voice.adsr_static_amp_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (f32(0.001000000));
				if (p.decay) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(p.decay), 0.000001)) * (1.0 - (f32(0.000000000))); else do envelope = (f32(0.000000000));
				voice.adsr_static_amp_release_level = envelope;
				if time_in_decay >= (p.decay) {
					voice.adsr_static_amp_stage = .Sustain;
				}
			case .Sustain:
				envelope = (f32(0.000000000));
				voice.adsr_static_amp_release_level = envelope;
				if envelope <= 0.0001 do voice.adsr_static_amp_stage = .Idle;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (f32(0.020000000)) > 0 do envelope = voice.adsr_static_amp_release_level * (1.0 - (time_in_release / math.max(f32(f32(0.020000000)), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_static_amp_stage = .Idle;
				}
			}
			vel_scale_static_amp: f32 = (1.0 - (f32(0.800000000))) + (f32(0.800000000)) * voice.velocity;
			node_static_amp_out = ((node_static_filter_out)) * envelope * (f32(1.000000000)) * vel_scale_static_amp;
		}

		output_left += node_static_amp_out
		output_right += node_static_amp_out
		if voice.adsr_static_amp_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	return output_left * f32(0.449999988), output_right * f32(0.449999988)
}
GW_Hat_Static_process_sequence :: proc(p: ^GW_Hat_Static_Processor) {
	if !p.playing do return
	samples_per_step_f := p.sample_rate * 60.0 / (p.bpm * 4.0)
	if p.samples_until_next_step == 0 {
		// Track "GW Hat Static" (16 steps)
		switch p.current_step % 16 {
		case 0:
			GW_Hat_Static_note_on(p, 42, 0.699999988, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 1:
			GW_Hat_Static_note_on(p, 42, 0.349999994, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 2:
			GW_Hat_Static_set_param(p, "decay", 0.119999997)
			GW_Hat_Static_note_on(p, 42, 0.550000012, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 3:
			GW_Hat_Static_note_on(p, 42, 0.349999994, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 4:
			GW_Hat_Static_note_on(p, 42, 0.699999988, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 5:
			GW_Hat_Static_note_on(p, 42, 0.349999994, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 6:
			GW_Hat_Static_set_param(p, "decay", 0.119999997)
			GW_Hat_Static_note_on(p, 42, 0.550000012, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 7:
			GW_Hat_Static_note_on(p, 42, 0.349999994, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 8:
			GW_Hat_Static_note_on(p, 42, 0.699999988, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 9:
			GW_Hat_Static_note_on(p, 42, 0.349999994, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 10:
			GW_Hat_Static_set_param(p, "decay", 0.119999997)
			GW_Hat_Static_note_on(p, 42, 0.550000012, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 11:
			GW_Hat_Static_note_on(p, 42, 0.349999994, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 12:
			GW_Hat_Static_note_on(p, 42, 0.699999988, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 13:
			GW_Hat_Static_note_on(p, 42, 0.349999994, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 14:
			GW_Hat_Static_set_param(p, "decay", 0.119999997)
			GW_Hat_Static_note_on(p, 42, 0.550000012, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 15:
			if next_float32(&p.prng) <= 0.699999988 {
				GW_Hat_Static_note_on(p, 42, 0.400000006, f32(1.000000000) * (60.0 / p.bpm / 4.0))
			}
		}
		p.current_step += 1
		if p.current_step >= 16 {
			if p.loop {
				p.current_step = 0
			} else {
				p.playing = false
			}
		}
		p.step_frac_acc += samples_per_step_f
		n_step := u64(math.max(p.step_frac_acc, 1.0))
		p.step_frac_acc -= f32(n_step)
		p.samples_until_next_step = n_step - 1
	} else {
		p.samples_until_next_step -= 1
	}
}

GW_Grunt_Swarm_Bass_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	adsr_grunt_amp_stage: ADSR_Stage,
	adsr_grunt_amp_release_level: f32,
	dist_grunt_dirt_tone: f32,
	filter_grunt_filter_low: f32,
	filter_grunt_filter_band: f32,
	osc_grunt_osc_phase: [1]f32,
}

GW_Grunt_Swarm_Bass_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [4]GW_Grunt_Swarm_Bass_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	amplitude: f32,
	attack: f32,
	cutoff: f32,
	decay: f32,
	drive: f32,
	mix: f32,
	release: f32,
	resonance: f32,
	sustain: f32,
}

GW_Grunt_Swarm_Bass_init :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 145.000000000
	p.prng.state = 12345
	p.loop = true
	p.amplitude = 0.500000000
	p.attack = 0.005000000
	p.cutoff = 750.000000000
	p.decay = 0.119999997
	p.drive = 8.000000000
	p.mix = 0.180000007
	p.release = 0.079999998
	p.resonance = 1.399999976
	p.sustain = 0.550000012
}

GW_Grunt_Swarm_Bass_note_on :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, note: u8, velocity: f32, duration: f32) {
	voice_idx := -1
	for i in 0..<4 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_age: f32 = -1.0
		for i in 0..<4 {
			if p.voices[i].age > oldest_age {
				oldest_age = p.voices[i].age
				voice_idx = i
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.000000000
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_grunt_amp_stage = .Attack
	v.adsr_grunt_amp_release_level = 0.0
	v.dist_grunt_dirt_tone = 0.0
	v.filter_grunt_filter_low = 0.0
	v.filter_grunt_filter_band = 0.0
	v.osc_grunt_osc_phase = {}
}

GW_Grunt_Swarm_Bass_note_off :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, note: u8) {
	best := -1
	best_age: f32 = -1.0
	for i in 0..<4 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_grunt_amp_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_grunt_amp_stage = .Release
	}
}

GW_Grunt_Swarm_Bass_trigger :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (p.attack) + (p.decay) > d do d = (p.attack) + (p.decay)
		if d <= 0.0 do d = 0.001
	}
	GW_Grunt_Swarm_Bass_note_on(p, note, velocity, d)
}

GW_Grunt_Swarm_Bass_feed_input :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

GW_Grunt_Swarm_Bass_start :: proc(p: ^GW_Grunt_Swarm_Bass_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

GW_Grunt_Swarm_Bass_stop :: proc(p: ^GW_Grunt_Swarm_Bass_Processor) {
	p.playing = false
}

GW_Grunt_Swarm_Bass_set_loop :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, loop: bool) {
	p.loop = loop
}

GW_Grunt_Swarm_Bass_is_playing :: proc(p: ^GW_Grunt_Swarm_Bass_Processor) -> bool {
	if p.playing do return true
	for i in 0..<4 {
		if p.voices[i].active do return true
	}
	return false
}

GW_Grunt_Swarm_Bass_set_amplitude :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.amplitude = v
}

GW_Grunt_Swarm_Bass_set_attack :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.attack = v
}

GW_Grunt_Swarm_Bass_set_cutoff :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, value: f32) {
	v := value
	if v < 20.000000000 do v = 20.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.cutoff = v
}

GW_Grunt_Swarm_Bass_set_decay :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.decay = v
}

GW_Grunt_Swarm_Bass_set_drive :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, value: f32) {
	v := value
	if v < 1.000000000 do v = 1.000000000
	if v > 100.000000000 do v = 100.000000000
	p.drive = v
}

GW_Grunt_Swarm_Bass_set_mix :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.mix = v
}

GW_Grunt_Swarm_Bass_set_release :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.release = v
}

GW_Grunt_Swarm_Bass_set_resonance :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, value: f32) {
	v := value
	if v < 0.100000001 do v = 0.100000001
	if v > 20.000000000 do v = 20.000000000
	p.resonance = v
}

GW_Grunt_Swarm_Bass_set_sustain :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.sustain = v
}

GW_Grunt_Swarm_Bass_PARAMS := []Skald_Param_Info{
	{"amplitude", 0.000000000, 1.000000000, 0.500000000, ""},
	{"attack", 0.001000000, 10.000000000, 0.005000000, "s"},
	{"cutoff", 20.000000000, 20000.000000000, 750.000000000, "Hz"},
	{"decay", 0.001000000, 10.000000000, 0.119999997, "s"},
	{"drive", 1.000000000, 100.000000000, 8.000000000, "x"},
	{"mix", 0.000000000, 1.000000000, 0.180000007, ""},
	{"release", 0.001000000, 10.000000000, 0.079999998, "s"},
	{"resonance", 0.100000001, 20.000000000, 1.399999976, "Q"},
	{"sustain", 0.000000000, 1.000000000, 0.550000012, ""},
}

GW_Grunt_Swarm_Bass_set_param :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, name: string, value: f32) -> bool {
	switch name {
	case "amplitude":
		GW_Grunt_Swarm_Bass_set_amplitude(p, value)
		return true
	case "attack":
		GW_Grunt_Swarm_Bass_set_attack(p, value)
		return true
	case "cutoff":
		GW_Grunt_Swarm_Bass_set_cutoff(p, value)
		return true
	case "decay":
		GW_Grunt_Swarm_Bass_set_decay(p, value)
		return true
	case "drive":
		GW_Grunt_Swarm_Bass_set_drive(p, value)
		return true
	case "mix":
		GW_Grunt_Swarm_Bass_set_mix(p, value)
		return true
	case "release":
		GW_Grunt_Swarm_Bass_set_release(p, value)
		return true
	case "resonance":
		GW_Grunt_Swarm_Bass_set_resonance(p, value)
		return true
	case "sustain":
		GW_Grunt_Swarm_Bass_set_sustain(p, value)
		return true
	}
	return false
}

GW_Grunt_Swarm_Bass_get_param :: proc(p: ^GW_Grunt_Swarm_Bass_Processor, name: string) -> (f32, bool) {
	switch name {
	case "amplitude":
		return p.amplitude, true
	case "attack":
		return p.attack, true
	case "cutoff":
		return p.cutoff, true
	case "decay":
		return p.decay, true
	case "drive":
		return p.drive, true
	case "mix":
		return p.mix, true
	case "release":
		return p.release, true
	case "resonance":
		return p.resonance, true
	case "sustain":
		return p.sustain, true
	}
	return 0.0, false
}

GW_Grunt_Swarm_Bass_process :: proc(p: ^GW_Grunt_Swarm_Bass_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	GW_Grunt_Swarm_Bass_process_sequence(p)
	p.total_samples += 1

	for v_idx in 0..<4 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_grunt_amp_stage != .Release && voice.adsr_grunt_amp_stage != .Idle {
				voice.adsr_grunt_amp_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_grunt_amp_out: f32 = 0.0
		node_grunt_dirt_out: f32 = 0.0
		node_grunt_filter_out: f32 = 0.0
		node_grunt_osc_out: f32 = 0.0
		node_grunt_output_out: f32 = 0.0

		// --- Oscillator Node grunt_osc (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (0.000000000);
				detuned_freq: f32 = (voice.current_freq) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads: f32 = f32(f32(0.000000000)) * (f32(math.PI) / 180.0);
				voice.osc_grunt_osc_phase[i] = math.mod(voice.osc_grunt_osc_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := math.mod(voice.osc_grunt_osc_phase[i] + phase_rads, 2 * f32(math.PI));
				unison_out += ((final_phase / f32(math.PI)) - 1.0);
			}
			if unison_count > 0 do node_grunt_osc_out = (unison_out / f32(unison_count)) * (p.amplitude);
		}

		// --- Filter Node grunt_filter (SVF) ---
		{
			cutoff_c_grunt_filter: f32 = math.clamp(f32(p.cutoff), 10.0, sample_rate * 0.16);
			f_grunt_filter := f32(2.0 * math.sin(f32(math.PI) * cutoff_c_grunt_filter / sample_rate));
			q_grunt_filter: f32 = math.clamp(1.0 / math.max(f32(p.resonance), 0.1), 0.05, 1.9 - f_grunt_filter);
			voice.filter_grunt_filter_low += f_grunt_filter * voice.filter_grunt_filter_band;
			high_grunt_filter := f32(((node_grunt_osc_out)) - voice.filter_grunt_filter_low - q_grunt_filter * voice.filter_grunt_filter_band);
			voice.filter_grunt_filter_band += f_grunt_filter * high_grunt_filter;
			node_grunt_filter_out = voice.filter_grunt_filter_low;
		}

		// --- ADSR Node grunt_amp ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_grunt_amp_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (p.attack) > 0 do envelope = voice.age / math.max(f32(p.attack), 0.000001); else do envelope = 1.0;
				voice.adsr_grunt_amp_release_level = envelope;
				if voice.age >= (p.attack) {
					voice.adsr_grunt_amp_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (p.attack);
				if (p.decay) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(p.decay), 0.000001)) * (1.0 - (p.sustain)); else do envelope = (p.sustain);
				voice.adsr_grunt_amp_release_level = envelope;
				if time_in_decay >= (p.decay) {
					voice.adsr_grunt_amp_stage = .Sustain;
				}
			case .Sustain:
				envelope = (p.sustain);
				voice.adsr_grunt_amp_release_level = envelope;
				if envelope <= 0.0001 do voice.adsr_grunt_amp_stage = .Idle;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (p.release) > 0 do envelope = voice.adsr_grunt_amp_release_level * (1.0 - (time_in_release / math.max(f32(p.release), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_grunt_amp_stage = .Idle;
				}
			}
			vel_scale_grunt_amp: f32 = (1.0 - (f32(0.600000000))) + (f32(0.600000000)) * voice.velocity;
			node_grunt_amp_out = ((node_grunt_filter_out)) * envelope * (f32(1.000000000)) * vel_scale_grunt_amp;
		}

		// --- Distortion Node grunt_dirt (classic) ---
		{
			dist_in_grunt_dirt: f32 = ((node_grunt_amp_out));
			dist_k_grunt_dirt: f32 = math.max(f32(p.drive), 1.0);
			dist_wet_grunt_dirt: f32 = (f32(math.PI) + dist_k_grunt_dirt) * dist_in_grunt_dirt / (f32(math.PI) + dist_k_grunt_dirt * abs(dist_in_grunt_dirt));
			tone_k_grunt_dirt: f32 = math.clamp(2.0 * f32(math.PI) * math.clamp(f32(f32(4500.000000000)), 100.0, 20000.0) / sample_rate, 0.001, 1.0);
			voice.dist_grunt_dirt_tone += tone_k_grunt_dirt * (dist_wet_grunt_dirt - voice.dist_grunt_dirt_tone);
			mix_grunt_dirt: f32 = math.clamp(f32(p.mix), 0.0, 1.0);
			node_grunt_dirt_out = dist_in_grunt_dirt * (1.0 - mix_grunt_dirt) + voice.dist_grunt_dirt_tone * mix_grunt_dirt;
		}

		output_left += node_grunt_dirt_out
		output_right += node_grunt_dirt_out
		if voice.adsr_grunt_amp_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	return output_left * f32(0.620000005), output_right * f32(0.620000005)
}
GW_Grunt_Swarm_Bass_process_sequence :: proc(p: ^GW_Grunt_Swarm_Bass_Processor) {
	if !p.playing do return
	samples_per_step_f := p.sample_rate * 60.0 / (p.bpm * 4.0)
	if p.samples_until_next_step == 0 {
		// Track "GW Grunt Swarm Bass" (16 steps)
		switch p.current_step % 16 {
		case 0:
			GW_Grunt_Swarm_Bass_note_on(p, 38, 1.000000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 2:
			GW_Grunt_Swarm_Bass_note_on(p, 38, 0.699999988, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 4:
			GW_Grunt_Swarm_Bass_note_on(p, 41, 0.850000024, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 6:
			GW_Grunt_Swarm_Bass_note_on(p, 38, 0.699999988, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 7:
			if next_float32(&p.prng) <= 0.500000000 {
				GW_Grunt_Swarm_Bass_note_on(p, 38, 0.500000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
			}
		case 8:
			GW_Grunt_Swarm_Bass_note_on(p, 43, 0.899999976, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 10:
			GW_Grunt_Swarm_Bass_note_on(p, 41, 0.750000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 12:
			GW_Grunt_Swarm_Bass_note_on(p, 40, 0.850000024, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 14:
			GW_Grunt_Swarm_Bass_note_on(p, 38, 0.800000012, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 15:
			if next_float32(&p.prng) <= 0.500000000 {
				GW_Grunt_Swarm_Bass_note_on(p, 40, 0.500000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
			}
		}
		p.current_step += 1
		if p.current_step >= 16 {
			if p.loop {
				p.current_step = 0
			} else {
				p.playing = false
			}
		}
		p.step_frac_acc += samples_per_step_f
		n_step := u64(math.max(p.step_frac_acc, 1.0))
		p.step_frac_acc -= f32(n_step)
		p.samples_until_next_step = n_step - 1
	} else {
		p.samples_until_next_step -= 1
	}
}

GW_Splitter_Echo_Stab_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	adsr_split_amp_stage: ADSR_Stage,
	adsr_split_amp_release_level: f32,
	filter_split_filter_low: f32,
	filter_split_filter_band: f32,
	osc_split_osc_phase: [1]f32,
}

GW_Splitter_Echo_Stab_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [5]GW_Splitter_Echo_Stab_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	delay_split_echo_buffer: [96000]f32,
	delay_split_echo_write_index: int,
	amplitude: f32,
	cutoff: f32,
	decay: f32,
	feedback: f32,
	mix: f32,
	pulseWidth: f32,
	release: f32,
	resonance: f32,
}

GW_Splitter_Echo_Stab_init :: proc(p: ^GW_Splitter_Echo_Stab_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 145.000000000
	p.prng.state = 12345
	p.loop = true
	p.amplitude = 0.449999988
	p.cutoff = 1500.000000000
	p.decay = 0.159999996
	p.feedback = 0.349999994
	p.mix = 0.300000012
	p.pulseWidth = 0.500000000
	p.release = 0.100000001
	p.resonance = 1.799999952
}

GW_Splitter_Echo_Stab_note_on :: proc(p: ^GW_Splitter_Echo_Stab_Processor, note: u8, velocity: f32, duration: f32) {
	voice_idx := -1
	for i in 0..<5 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_age: f32 = -1.0
		for i in 0..<5 {
			if p.voices[i].age > oldest_age {
				oldest_age = p.voices[i].age
				voice_idx = i
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.000000000
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_split_amp_stage = .Attack
	v.adsr_split_amp_release_level = 0.0
	v.filter_split_filter_low = 0.0
	v.filter_split_filter_band = 0.0
	v.osc_split_osc_phase = {}
}

GW_Splitter_Echo_Stab_note_off :: proc(p: ^GW_Splitter_Echo_Stab_Processor, note: u8) {
	best := -1
	best_age: f32 = -1.0
	for i in 0..<5 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_split_amp_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_split_amp_stage = .Release
	}
}

GW_Splitter_Echo_Stab_trigger :: proc(p: ^GW_Splitter_Echo_Stab_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (f32(0.003000000)) + (p.decay) > d do d = (f32(0.003000000)) + (p.decay)
		if d <= 0.0 do d = 0.001
	}
	GW_Splitter_Echo_Stab_note_on(p, note, velocity, d)
}

GW_Splitter_Echo_Stab_feed_input :: proc(p: ^GW_Splitter_Echo_Stab_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

GW_Splitter_Echo_Stab_start :: proc(p: ^GW_Splitter_Echo_Stab_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

GW_Splitter_Echo_Stab_stop :: proc(p: ^GW_Splitter_Echo_Stab_Processor) {
	p.playing = false
}

GW_Splitter_Echo_Stab_set_loop :: proc(p: ^GW_Splitter_Echo_Stab_Processor, loop: bool) {
	p.loop = loop
}

GW_Splitter_Echo_Stab_is_playing :: proc(p: ^GW_Splitter_Echo_Stab_Processor) -> bool {
	if p.playing do return true
	for i in 0..<5 {
		if p.voices[i].active do return true
	}
	return false
}

GW_Splitter_Echo_Stab_set_amplitude :: proc(p: ^GW_Splitter_Echo_Stab_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.amplitude = v
}

GW_Splitter_Echo_Stab_set_cutoff :: proc(p: ^GW_Splitter_Echo_Stab_Processor, value: f32) {
	v := value
	if v < 20.000000000 do v = 20.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.cutoff = v
}

GW_Splitter_Echo_Stab_set_decay :: proc(p: ^GW_Splitter_Echo_Stab_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.decay = v
}

GW_Splitter_Echo_Stab_set_feedback :: proc(p: ^GW_Splitter_Echo_Stab_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 0.990000010 do v = 0.990000010
	p.feedback = v
}

GW_Splitter_Echo_Stab_set_mix :: proc(p: ^GW_Splitter_Echo_Stab_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.mix = v
}

GW_Splitter_Echo_Stab_set_pulseWidth :: proc(p: ^GW_Splitter_Echo_Stab_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.pulseWidth = v
}

GW_Splitter_Echo_Stab_set_release :: proc(p: ^GW_Splitter_Echo_Stab_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.release = v
}

GW_Splitter_Echo_Stab_set_resonance :: proc(p: ^GW_Splitter_Echo_Stab_Processor, value: f32) {
	v := value
	if v < 0.100000001 do v = 0.100000001
	if v > 20.000000000 do v = 20.000000000
	p.resonance = v
}

GW_Splitter_Echo_Stab_PARAMS := []Skald_Param_Info{
	{"amplitude", 0.000000000, 1.000000000, 0.449999988, ""},
	{"cutoff", 20.000000000, 20000.000000000, 1500.000000000, "Hz"},
	{"decay", 0.001000000, 10.000000000, 0.159999996, "s"},
	{"feedback", 0.000000000, 0.990000010, 0.349999994, ""},
	{"mix", 0.000000000, 1.000000000, 0.300000012, ""},
	{"pulseWidth", 0.000000000, 1.000000000, 0.500000000, ""},
	{"release", 0.001000000, 10.000000000, 0.100000001, "s"},
	{"resonance", 0.100000001, 20.000000000, 1.799999952, "Q"},
}

GW_Splitter_Echo_Stab_set_param :: proc(p: ^GW_Splitter_Echo_Stab_Processor, name: string, value: f32) -> bool {
	switch name {
	case "amplitude":
		GW_Splitter_Echo_Stab_set_amplitude(p, value)
		return true
	case "cutoff":
		GW_Splitter_Echo_Stab_set_cutoff(p, value)
		return true
	case "decay":
		GW_Splitter_Echo_Stab_set_decay(p, value)
		return true
	case "feedback":
		GW_Splitter_Echo_Stab_set_feedback(p, value)
		return true
	case "mix":
		GW_Splitter_Echo_Stab_set_mix(p, value)
		return true
	case "pulseWidth":
		GW_Splitter_Echo_Stab_set_pulseWidth(p, value)
		return true
	case "release":
		GW_Splitter_Echo_Stab_set_release(p, value)
		return true
	case "resonance":
		GW_Splitter_Echo_Stab_set_resonance(p, value)
		return true
	}
	return false
}

GW_Splitter_Echo_Stab_get_param :: proc(p: ^GW_Splitter_Echo_Stab_Processor, name: string) -> (f32, bool) {
	switch name {
	case "amplitude":
		return p.amplitude, true
	case "cutoff":
		return p.cutoff, true
	case "decay":
		return p.decay, true
	case "feedback":
		return p.feedback, true
	case "mix":
		return p.mix, true
	case "pulseWidth":
		return p.pulseWidth, true
	case "release":
		return p.release, true
	case "resonance":
		return p.resonance, true
	}
	return 0.0, false
}

GW_Splitter_Echo_Stab_process :: proc(p: ^GW_Splitter_Echo_Stab_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	GW_Splitter_Echo_Stab_process_sequence(p)
	p.total_samples += 1

	node_split_amp_out_vsum: f32 = 0.0
	for v_idx in 0..<5 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_split_amp_stage != .Release && voice.adsr_split_amp_stage != .Idle {
				voice.adsr_split_amp_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_split_amp_out: f32 = 0.0
		node_split_filter_out: f32 = 0.0
		node_split_osc_out: f32 = 0.0

		// --- Oscillator Node split_osc (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (0.000000000);
				detuned_freq: f32 = (voice.current_freq) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads: f32 = f32(f32(0.000000000)) * (f32(math.PI) / 180.0);
				voice.osc_split_osc_phase[i] = math.mod(voice.osc_split_osc_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := math.mod(voice.osc_split_osc_phase[i] + phase_rads, 2 * f32(math.PI));
				if final_phase < 2 * f32(math.PI) * math.clamp(f32(p.pulseWidth), 0.01, 0.99) do unison_out += 1.0; else do unison_out -= 1.0;
			}
			if unison_count > 0 do node_split_osc_out = (unison_out / f32(unison_count)) * (p.amplitude);
		}

		// --- Filter Node split_filter (SVF) ---
		{
			cutoff_c_split_filter: f32 = math.clamp(f32(p.cutoff), 10.0, sample_rate * 0.16);
			f_split_filter := f32(2.0 * math.sin(f32(math.PI) * cutoff_c_split_filter / sample_rate));
			q_split_filter: f32 = math.clamp(1.0 / math.max(f32(p.resonance), 0.1), 0.05, 1.9 - f_split_filter);
			voice.filter_split_filter_low += f_split_filter * voice.filter_split_filter_band;
			high_split_filter := f32(((node_split_osc_out)) - voice.filter_split_filter_low - q_split_filter * voice.filter_split_filter_band);
			voice.filter_split_filter_band += f_split_filter * high_split_filter;
			node_split_filter_out = voice.filter_split_filter_low;
		}

		// --- ADSR Node split_amp ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_split_amp_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (f32(0.003000000)) > 0 do envelope = voice.age / math.max(f32(f32(0.003000000)), 0.000001); else do envelope = 1.0;
				voice.adsr_split_amp_release_level = envelope;
				if voice.age >= (f32(0.003000000)) {
					voice.adsr_split_amp_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (f32(0.003000000));
				if (p.decay) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(p.decay), 0.000001)) * (1.0 - (f32(0.000000000))); else do envelope = (f32(0.000000000));
				voice.adsr_split_amp_release_level = envelope;
				if time_in_decay >= (p.decay) {
					voice.adsr_split_amp_stage = .Sustain;
				}
			case .Sustain:
				envelope = (f32(0.000000000));
				voice.adsr_split_amp_release_level = envelope;
				if envelope <= 0.0001 do voice.adsr_split_amp_stage = .Idle;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (p.release) > 0 do envelope = voice.adsr_split_amp_release_level * (1.0 - (time_in_release / math.max(f32(p.release), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_split_amp_stage = .Idle;
				}
			}
			vel_scale_split_amp: f32 = (1.0 - (f32(0.700000000))) + (f32(0.700000000)) * voice.velocity;
			node_split_amp_out = ((node_split_filter_out)) * envelope * (f32(1.000000000)) * vel_scale_split_amp;
		}

		node_split_amp_out_vsum += node_split_amp_out
		if voice.adsr_split_amp_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}

	// --- Bus effects (once per sample, post voice sum) ---
	{
		node_split_amp_out := node_split_amp_out_vsum
		node_split_echo_out: f32 = 0.0
		// --- Delay Node split_echo ---
		{
			delay_samples_split_echo := int(math.clamp((((60.0 / p.bpm) * 0.500000000)) * sample_rate, 1, 96000-1));
			read_index_split_echo := (p.delay_split_echo_write_index - delay_samples_split_echo + len(p.delay_split_echo_buffer)) % len(p.delay_split_echo_buffer);
			delayed_sample_split_echo := p.delay_split_echo_buffer[read_index_split_echo];
			p.delay_split_echo_buffer[p.delay_split_echo_write_index] = ((node_split_amp_out)) + delayed_sample_split_echo * math.clamp(f32(p.feedback), 0.0, 0.95);
			p.delay_split_echo_write_index = (p.delay_split_echo_write_index + 1) % len(p.delay_split_echo_buffer);
			node_split_echo_out = ((node_split_amp_out)) * (1.0 - (p.mix)) + delayed_sample_split_echo * (p.mix);
		}

		output_left += node_split_echo_out
		output_right += node_split_echo_out
	}
	return output_left * f32(0.579999983), output_right * f32(0.579999983)
}
GW_Splitter_Echo_Stab_process_sequence :: proc(p: ^GW_Splitter_Echo_Stab_Processor) {
	if !p.playing do return
	samples_per_step_f := p.sample_rate * 60.0 / (p.bpm * 4.0)
	if p.samples_until_next_step == 0 {
		// Track "GW Splitter Echo Stab" (16 steps)
		switch p.current_step % 16 {
		case 0:
			GW_Splitter_Echo_Stab_note_on(p, 50, 0.899999976, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 3:
			GW_Splitter_Echo_Stab_note_on(p, 53, 0.750000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 6:
			GW_Splitter_Echo_Stab_note_on(p, 50, 0.850000024, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 10:
			GW_Splitter_Echo_Stab_note_on(p, 45, 0.800000012, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 12:
			GW_Splitter_Echo_Stab_note_on(p, 48, 0.899999976, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 15:
			if next_float32(&p.prng) <= 0.600000024 {
				GW_Splitter_Echo_Stab_note_on(p, 50, 0.600000024, f32(1.000000000) * (60.0 / p.bpm / 4.0))
			}
		}
		p.current_step += 1
		if p.current_step >= 16 {
			if p.loop {
				p.current_step = 0
			} else {
				p.playing = false
			}
		}
		p.step_frac_acc += samples_per_step_f
		n_step := u64(math.max(p.step_frac_acc, 1.0))
		p.step_frac_acc -= f32(n_step)
		p.samples_until_next_step = n_step - 1
	} else {
		p.samples_until_next_step -= 1
	}
}

Tuba_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	adsr_tuba_amp_stage: ADSR_Stage,
	adsr_tuba_amp_release_level: f32,
	adsr_tuba_blow_stage: ADSR_Stage,
	adsr_tuba_blow_release_level: f32,
	filter_tuba_filter_low: f32,
	filter_tuba_filter_band: f32,
	osc_tuba_osc_phase: [1]f32,
	lfo_tuba_vibrato_phase: f32,
}

Tuba_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [8]Tuba_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	Amp_attack: f32,
	Amp_decay: f32,
	Amp_depth: f32,
	Amp_release: f32,
	Amp_sustain: f32,
	Blow_attack: f32,
	Blow_decay: f32,
	Blow_depth: f32,
	Blow_release: f32,
	Blow_sustain: f32,
	Buzz_amplitude: f32,
	Vibrato_amplitude: f32,
	cutoff: f32,
	frequency: f32,
	outMax: f32,
	resonance: f32,
	velocitySensitivity: f32,
}

Tuba_init :: proc(p: ^Tuba_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 145.000000000
	p.prng.state = 12345
	p.loop = true
	p.Amp_attack = 0.079999998
	p.Amp_decay = 0.100000001
	p.Amp_depth = 1.000000000
	p.Amp_release = 0.180000007
	p.Amp_sustain = 0.850000024
	p.Blow_attack = 0.090000004
	p.Blow_decay = 0.250000000
	p.Blow_depth = 1.000000000
	p.Blow_release = 0.150000006
	p.Blow_sustain = 0.349999994
	p.Buzz_amplitude = 0.600000024
	p.Vibrato_amplitude = 0.020000000
	p.cutoff = 220.000000000
	p.frequency = 5.000000000
	p.outMax = 700.000000000
	p.resonance = 0.800000012
	p.velocitySensitivity = 0.699999988
}

Tuba_note_on :: proc(p: ^Tuba_Processor, note: u8, velocity: f32, duration: f32) {
	voice_idx := -1
	for i in 0..<8 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_age: f32 = -1.0
		for i in 0..<8 {
			if p.voices[i].age > oldest_age {
				oldest_age = p.voices[i].age
				voice_idx = i
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.039999999
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.adsr_tuba_amp_stage = .Attack
	v.adsr_tuba_amp_release_level = 0.0
	v.adsr_tuba_blow_stage = .Attack
	v.adsr_tuba_blow_release_level = 0.0
	v.filter_tuba_filter_low = 0.0
	v.filter_tuba_filter_band = 0.0
	v.osc_tuba_osc_phase = {}
}

Tuba_note_off :: proc(p: ^Tuba_Processor, note: u8) {
	best := -1
	best_age: f32 = -1.0
	for i in 0..<8 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_tuba_amp_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_tuba_amp_stage = .Release
		p.voices[best].adsr_tuba_blow_stage = .Release
	}
}

Tuba_trigger :: proc(p: ^Tuba_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (p.Amp_attack) + (p.Amp_decay) > d do d = (p.Amp_attack) + (p.Amp_decay)
		if (p.Blow_attack) + (p.Blow_decay) > d do d = (p.Blow_attack) + (p.Blow_decay)
		if d <= 0.0 do d = 0.001
	}
	Tuba_note_on(p, note, velocity, d)
}

Tuba_feed_input :: proc(p: ^Tuba_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

Tuba_start :: proc(p: ^Tuba_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

Tuba_stop :: proc(p: ^Tuba_Processor) {
	p.playing = false
}

Tuba_set_loop :: proc(p: ^Tuba_Processor, loop: bool) {
	p.loop = loop
}

Tuba_is_playing :: proc(p: ^Tuba_Processor) -> bool {
	if p.playing do return true
	for i in 0..<8 {
		if p.voices[i].active do return true
	}
	return false
}

Tuba_set_Amp_attack :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Amp_attack = v
}

Tuba_set_Amp_decay :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Amp_decay = v
}

Tuba_set_Amp_depth :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Amp_depth = v
}

Tuba_set_Amp_release :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Amp_release = v
}

Tuba_set_Amp_sustain :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Amp_sustain = v
}

Tuba_set_Blow_attack :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Blow_attack = v
}

Tuba_set_Blow_decay :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Blow_decay = v
}

Tuba_set_Blow_depth :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Blow_depth = v
}

Tuba_set_Blow_release :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Blow_release = v
}

Tuba_set_Blow_sustain :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Blow_sustain = v
}

Tuba_set_Buzz_amplitude :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Buzz_amplitude = v
}

Tuba_set_Vibrato_amplitude :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.Vibrato_amplitude = v
}

Tuba_set_cutoff :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 20.000000000 do v = 20.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.cutoff = v
}

Tuba_set_frequency :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.010000000 do v = 0.010000000
	if v > 100.000000000 do v = 100.000000000
	p.frequency = v
}

Tuba_set_outMax :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < -1000000.000000000 do v = -1000000.000000000
	if v > 1000000.000000000 do v = 1000000.000000000
	p.outMax = v
}

Tuba_set_resonance :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.100000001 do v = 0.100000001
	if v > 20.000000000 do v = 20.000000000
	p.resonance = v
}

Tuba_set_velocitySensitivity :: proc(p: ^Tuba_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.velocitySensitivity = v
}

Tuba_PARAMS := []Skald_Param_Info{
	{"Amp_attack", 0.001000000, 10.000000000, 0.079999998, "s"},
	{"Amp_decay", 0.001000000, 10.000000000, 0.100000001, "s"},
	{"Amp_depth", 0.000000000, 1.000000000, 1.000000000, ""},
	{"Amp_release", 0.001000000, 10.000000000, 0.180000007, "s"},
	{"Amp_sustain", 0.000000000, 1.000000000, 0.850000024, ""},
	{"Blow_attack", 0.001000000, 10.000000000, 0.090000004, "s"},
	{"Blow_decay", 0.001000000, 10.000000000, 0.250000000, "s"},
	{"Blow_depth", 0.000000000, 1.000000000, 1.000000000, ""},
	{"Blow_release", 0.001000000, 10.000000000, 0.150000006, "s"},
	{"Blow_sustain", 0.000000000, 1.000000000, 0.349999994, ""},
	{"Buzz_amplitude", 0.000000000, 1.000000000, 0.600000024, ""},
	{"Vibrato_amplitude", 0.000000000, 20000.000000000, 0.020000000, ""},
	{"cutoff", 20.000000000, 20000.000000000, 220.000000000, "Hz"},
	{"frequency", 0.010000000, 100.000000000, 5.000000000, "Hz"},
	{"outMax", -1000000.000000000, 1000000.000000000, 700.000000000, ""},
	{"resonance", 0.100000001, 20.000000000, 0.800000012, "Q"},
	{"velocitySensitivity", 0.000000000, 1.000000000, 0.699999988, ""},
}

Tuba_set_param :: proc(p: ^Tuba_Processor, name: string, value: f32) -> bool {
	switch name {
	case "Amp_attack":
		Tuba_set_Amp_attack(p, value)
		return true
	case "Amp_decay":
		Tuba_set_Amp_decay(p, value)
		return true
	case "Amp_depth":
		Tuba_set_Amp_depth(p, value)
		return true
	case "Amp_release":
		Tuba_set_Amp_release(p, value)
		return true
	case "Amp_sustain":
		Tuba_set_Amp_sustain(p, value)
		return true
	case "Blow_attack":
		Tuba_set_Blow_attack(p, value)
		return true
	case "Blow_decay":
		Tuba_set_Blow_decay(p, value)
		return true
	case "Blow_depth":
		Tuba_set_Blow_depth(p, value)
		return true
	case "Blow_release":
		Tuba_set_Blow_release(p, value)
		return true
	case "Blow_sustain":
		Tuba_set_Blow_sustain(p, value)
		return true
	case "Buzz_amplitude":
		Tuba_set_Buzz_amplitude(p, value)
		return true
	case "Vibrato_amplitude":
		Tuba_set_Vibrato_amplitude(p, value)
		return true
	case "cutoff":
		Tuba_set_cutoff(p, value)
		return true
	case "frequency":
		Tuba_set_frequency(p, value)
		return true
	case "outMax":
		Tuba_set_outMax(p, value)
		return true
	case "resonance":
		Tuba_set_resonance(p, value)
		return true
	case "velocitySensitivity":
		Tuba_set_velocitySensitivity(p, value)
		return true
	}
	return false
}

Tuba_get_param :: proc(p: ^Tuba_Processor, name: string) -> (f32, bool) {
	switch name {
	case "Amp_attack":
		return p.Amp_attack, true
	case "Amp_decay":
		return p.Amp_decay, true
	case "Amp_depth":
		return p.Amp_depth, true
	case "Amp_release":
		return p.Amp_release, true
	case "Amp_sustain":
		return p.Amp_sustain, true
	case "Blow_attack":
		return p.Blow_attack, true
	case "Blow_decay":
		return p.Blow_decay, true
	case "Blow_depth":
		return p.Blow_depth, true
	case "Blow_release":
		return p.Blow_release, true
	case "Blow_sustain":
		return p.Blow_sustain, true
	case "Buzz_amplitude":
		return p.Buzz_amplitude, true
	case "Vibrato_amplitude":
		return p.Vibrato_amplitude, true
	case "cutoff":
		return p.cutoff, true
	case "frequency":
		return p.frequency, true
	case "outMax":
		return p.outMax, true
	case "resonance":
		return p.resonance, true
	case "velocitySensitivity":
		return p.velocitySensitivity, true
	}
	return 0.0, false
}

Tuba_process :: proc(p: ^Tuba_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	Tuba_process_sequence(p)
	p.total_samples += 1

	for v_idx in 0..<8 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.current_freq != voice.target_freq {
			glide_k := 1.0 / math.max(voice.glide_time * sample_rate, 1.0)
			if glide_k > 1.0 do glide_k = 1.0
			voice.current_freq += (voice.target_freq - voice.current_freq) * glide_k
			if abs(voice.target_freq - voice.current_freq) < 0.1 do voice.current_freq = voice.target_freq
		}
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_tuba_amp_stage != .Release && voice.adsr_tuba_amp_stage != .Idle {
				voice.adsr_tuba_amp_stage = .Release
				voice.time_released = voice.age
			}
			if voice.adsr_tuba_blow_stage != .Release && voice.adsr_tuba_blow_stage != .Idle {
				voice.adsr_tuba_blow_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_tuba_amp_out: f32 = 0.0
		node_tuba_blow_out: f32 = 0.0
		node_tuba_blow_map_out: f32 = 0.0
		node_tuba_filter_out: f32 = 0.0
		node_tuba_osc_out: f32 = 0.0
		node_tuba_output_out: f32 = 0.0
		node_tuba_vibrato_out: f32 = 0.0

		// --- ADSR Node tuba_blow ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_tuba_blow_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (p.Blow_attack) > 0 do envelope = voice.age / math.max(f32(p.Blow_attack), 0.000001); else do envelope = 1.0;
				voice.adsr_tuba_blow_release_level = envelope;
				if voice.age >= (p.Blow_attack) {
					voice.adsr_tuba_blow_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (p.Blow_attack);
				if (p.Blow_decay) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(p.Blow_decay), 0.000001)) * (1.0 - (p.Blow_sustain)); else do envelope = (p.Blow_sustain);
				voice.adsr_tuba_blow_release_level = envelope;
				if time_in_decay >= (p.Blow_decay) {
					voice.adsr_tuba_blow_stage = .Sustain;
				}
			case .Sustain:
				envelope = (p.Blow_sustain);
				voice.adsr_tuba_blow_release_level = envelope;
				if envelope <= 0.0001 do voice.adsr_tuba_blow_stage = .Idle;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (p.Blow_release) > 0 do envelope = voice.adsr_tuba_blow_release_level * (1.0 - (time_in_release / math.max(f32(p.Blow_release), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_tuba_blow_stage = .Idle;
				}
			}
			vel_scale_tuba_blow: f32 = (1.0 - (f32(0.500000000))) + (f32(0.500000000)) * voice.velocity;
			node_tuba_blow_out = (1.0) * envelope * (p.Blow_depth) * vel_scale_tuba_blow;
		}

		// --- LFO Node tuba_vibrato ---
		voice.lfo_tuba_vibrato_phase = math.mod(voice.lfo_tuba_vibrato_phase + (2 * f32(math.PI) * (p.frequency) / sample_rate), 2 * f32(math.PI));
		if voice.lfo_tuba_vibrato_phase < 0.0 do voice.lfo_tuba_vibrato_phase += 2 * f32(math.PI);
		node_tuba_vibrato_out = math.sin(voice.lfo_tuba_vibrato_phase) * (p.Vibrato_amplitude);

		// --- Mapper Node tuba_blow_map ---
		{
			in_range_tuba_blow_map: f32 = f32(f32(1.000000000)) - f32(f32(0.000000000));
			if in_range_tuba_blow_map == 0.0 do in_range_tuba_blow_map = 1.0;
			node_tuba_blow_map_out = math.lerp(f32(f32(0.000000000)), f32(p.outMax), math.clamp((f32((node_tuba_blow_out)) - f32(f32(0.000000000))) / in_range_tuba_blow_map, 0.0, 1.0));
		}

		// --- Oscillator Node tuba_osc (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (0.000000000);
				detuned_freq: f32 = ((voice.current_freq) * math.pow(2.0, math.clamp(f32(node_tuba_vibrato_out), -10.0, 10.0))) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads: f32 = f32(f32(0.000000000)) * (f32(math.PI) / 180.0);
				voice.osc_tuba_osc_phase[i] = math.mod(voice.osc_tuba_osc_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := math.mod(voice.osc_tuba_osc_phase[i] + phase_rads, 2 * f32(math.PI));
				unison_out += ((final_phase / f32(math.PI)) - 1.0);
			}
			if unison_count > 0 do node_tuba_osc_out = (unison_out / f32(unison_count)) * (p.Buzz_amplitude);
		}

		// --- Filter Node tuba_filter (SVF) ---
		{
			cutoff_c_tuba_filter: f32 = math.clamp(f32((p.cutoff) + (node_tuba_blow_map_out)), 10.0, sample_rate * 0.16);
			f_tuba_filter := f32(2.0 * math.sin(f32(math.PI) * cutoff_c_tuba_filter / sample_rate));
			q_tuba_filter: f32 = math.clamp(1.0 / math.max(f32(p.resonance), 0.1), 0.05, 1.9 - f_tuba_filter);
			voice.filter_tuba_filter_low += f_tuba_filter * voice.filter_tuba_filter_band;
			high_tuba_filter := f32(((node_tuba_osc_out)) - voice.filter_tuba_filter_low - q_tuba_filter * voice.filter_tuba_filter_band);
			voice.filter_tuba_filter_band += f_tuba_filter * high_tuba_filter;
			node_tuba_filter_out = voice.filter_tuba_filter_low;
		}

		// --- ADSR Node tuba_amp ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_tuba_amp_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (p.Amp_attack) > 0 do envelope = voice.age / math.max(f32(p.Amp_attack), 0.000001); else do envelope = 1.0;
				voice.adsr_tuba_amp_release_level = envelope;
				if voice.age >= (p.Amp_attack) {
					voice.adsr_tuba_amp_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (p.Amp_attack);
				if (p.Amp_decay) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(p.Amp_decay), 0.000001)) * (1.0 - (p.Amp_sustain)); else do envelope = (p.Amp_sustain);
				voice.adsr_tuba_amp_release_level = envelope;
				if time_in_decay >= (p.Amp_decay) {
					voice.adsr_tuba_amp_stage = .Sustain;
				}
			case .Sustain:
				envelope = (p.Amp_sustain);
				voice.adsr_tuba_amp_release_level = envelope;
				if envelope <= 0.0001 do voice.adsr_tuba_amp_stage = .Idle;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (p.Amp_release) > 0 do envelope = voice.adsr_tuba_amp_release_level * (1.0 - (time_in_release / math.max(f32(p.Amp_release), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_tuba_amp_stage = .Idle;
				}
			}
			vel_scale_tuba_amp: f32 = (1.0 - (p.velocitySensitivity)) + (p.velocitySensitivity) * voice.velocity;
			node_tuba_amp_out = ((node_tuba_filter_out)) * envelope * (p.Amp_depth) * vel_scale_tuba_amp;
		}

		output_left += node_tuba_amp_out
		output_right += node_tuba_amp_out
		if voice.adsr_tuba_amp_stage != .Idle do voice_busy = true
		if voice.adsr_tuba_blow_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}
	return output_left * f32(0.850000024), output_right * f32(0.850000024)
}
Tuba_process_sequence :: proc(p: ^Tuba_Processor) {
	if !p.playing do return
	samples_per_step_f := p.sample_rate * 60.0 / (p.bpm * 4.0)
	if p.samples_until_next_step == 0 {
		// Track "Tuba" (16 steps)
		switch p.current_step % 16 {
		case 6:
			Tuba_note_on(p, 60, 1.000000000, f32(3.000000000) * (60.0 / p.bpm / 4.0))
		case 14:
			Tuba_note_on(p, 60, 1.000000000, f32(2.000000000) * (60.0 / p.bpm / 4.0))
		}
		p.current_step += 1
		if p.current_step >= 16 {
			if p.loop {
				p.current_step = 0
			} else {
				p.playing = false
			}
		}
		p.step_frac_acc += samples_per_step_f
		n_step := u64(math.max(p.step_frac_acc, 1.0))
		p.step_frac_acc -= f32(n_step)
		p.samples_until_next_step = n_step - 1
	} else {
		p.samples_until_next_step -= 1
	}
}

Growly_Sax_Voice_State :: struct {
	active: bool,
	note: u8,
	velocity: f32,
	age: f32,
	time_released: f32,
	current_freq: f32,
	target_freq: f32,
	glide_time: f32,
	duration: f32,
	filter_growl_air_low: f32,
	filter_growl_air_band: f32,
	adsr_growl_amp_stage: ADSR_Stage,
	adsr_growl_amp_release_level: f32,
	filter_growl_body_low: f32,
	filter_growl_body_band: f32,
	noise_growl_breath_rng: PRNG_State,
	noise_growl_breath_p0: f32,
	noise_growl_breath_p1: f32,
	noise_growl_breath_p2: f32,
	dist_growl_drive_tone: f32,
	filter_growl_formant_low: f32,
	filter_growl_formant_band: f32,
	adsr_growl_puff_stage: ADSR_Stage,
	adsr_growl_puff_release_level: f32,
	osc_growl_reed_phase: [1]f32,
	adsr_growl_scoop_stage: ADSR_Stage,
	adsr_growl_scoop_release_level: f32,
	lfo_growl_vibrato_phase: f32,
}

Growly_Sax_Processor :: struct {
	sample_rate: f32,
	bpm: f32,
	voices: [4]Growly_Sax_Voice_State,
	prng: PRNG_State,
	total_samples: u64,
	playing: bool,
	loop: bool,
	current_step: u64,
	samples_until_next_step: u64,
	step_frac_acc: f32,
	ext_in_l: f32,
	ext_in_r: f32,
	delay_growl_reverb_buffer: [96000]f32,
	delay_growl_reverb_write_index: int,
	Air_cutoff: f32,
	Air_resonance: f32,
	Amp_attack: f32,
	Amp_decay: f32,
	Amp_depth: f32,
	Amp_release: f32,
	Amp_sustain: f32,
	Body_cutoff: f32,
	Body_resonance: f32,
	Breath_amplitude: f32,
	Expression_mix: f32,
	Formant_cutoff: f32,
	Formant_resonance: f32,
	Puff_attack: f32,
	Puff_decay: f32,
	Puff_depth: f32,
	Puff_release: f32,
	Puff_sustain: f32,
	Reed_amplitude: f32,
	Room_decay: f32,
	Room_mix: f32,
	Scoop_attack: f32,
	Scoop_depth: f32,
	Scoop_release: f32,
	Scoop_sustain: f32,
	Vibrato_amplitude: f32,
	drive: f32,
	frequency: f32,
	outMin: f32,
	tone: f32,
	velocitySensitivity: f32,
}

Growly_Sax_init :: proc(p: ^Growly_Sax_Processor, sr: f32) {
	p.sample_rate = sr
	p.bpm = 145.000000000
	p.prng.state = 12345
	p.loop = true
	for i in 0..<4 {
		v := &p.voices[i]
		v.noise_growl_breath_rng.state = u32(0xC0FFEE01) ~ u32(i + 1) * 2654435761
	}
	p.Air_cutoff = 4500.000000000
	p.Air_resonance = 1.000000000
	p.Amp_attack = 0.050000001
	p.Amp_decay = 0.180000007
	p.Amp_depth = 1.000000000
	p.Amp_release = 0.140000001
	p.Amp_sustain = 0.800000012
	p.Body_cutoff = 1600.000000000
	p.Body_resonance = 1.200000048
	p.Breath_amplitude = 0.150000006
	p.Expression_mix = 0.250000000
	p.Formant_cutoff = 1100.000000000
	p.Formant_resonance = 2.500000000
	p.Puff_attack = 0.010000000
	p.Puff_decay = 0.119999997
	p.Puff_depth = 1.000000000
	p.Puff_release = 0.079999998
	p.Puff_sustain = 0.250000000
	p.Reed_amplitude = 0.550000012
	p.Room_decay = 1.500000000
	p.Room_mix = 0.150000006
	p.Scoop_attack = 0.070000000
	p.Scoop_depth = 1.000000000
	p.Scoop_release = 0.050000001
	p.Scoop_sustain = 1.000000000
	p.Vibrato_amplitude = 0.020000000
	p.drive = 18.000000000
	p.frequency = 5.500000000
	p.outMin = -0.119999997
	p.tone = 5000.000000000
	p.velocitySensitivity = 0.800000012
}

Growly_Sax_note_on :: proc(p: ^Growly_Sax_Processor, note: u8, velocity: f32, duration: f32) {
	voice_idx := -1
	for i in 0..<4 {
		if !p.voices[i].active {
			voice_idx = i
			break
		}
	}
	stolen := false
	if voice_idx == -1 {
		stolen = true
		oldest_age: f32 = -1.0
		for i in 0..<4 {
			if p.voices[i].age > oldest_age {
				oldest_age = p.voices[i].age
				voice_idx = i
			}
		}
	}

	v := &p.voices[voice_idx]
	prev_freq := v.current_freq
	v.active = true
	v.note = note
	v.velocity = velocity
	v.age = 0.0
	v.time_released = 0.0
	freq := 440.0 * math.pow(2.0, (f32(note) - 69.0) / 12.0)
	v.target_freq = freq
	v.glide_time = 0.039999999
	if stolen && v.glide_time > 0.0 && prev_freq > 0.0 {
		v.current_freq = prev_freq
	} else {
		v.current_freq = freq
	}
	v.duration = duration
	v.filter_growl_air_low = 0.0
	v.filter_growl_air_band = 0.0
	v.adsr_growl_amp_stage = .Attack
	v.adsr_growl_amp_release_level = 0.0
	v.filter_growl_body_low = 0.0
	v.filter_growl_body_band = 0.0
	v.dist_growl_drive_tone = 0.0
	v.filter_growl_formant_low = 0.0
	v.filter_growl_formant_band = 0.0
	v.adsr_growl_puff_stage = .Attack
	v.adsr_growl_puff_release_level = 0.0
	v.osc_growl_reed_phase = {}
	v.adsr_growl_scoop_stage = .Attack
	v.adsr_growl_scoop_release_level = 0.0
}

Growly_Sax_note_off :: proc(p: ^Growly_Sax_Processor, note: u8) {
	best := -1
	best_age: f32 = -1.0
	for i in 0..<4 {
		if p.voices[i].active && p.voices[i].note == note {
			if p.voices[i].adsr_growl_amp_stage == .Release do continue
			if p.voices[i].age > best_age {
				best_age = p.voices[i].age
				best = i
			}
		}
	}
	if best >= 0 {
		p.voices[best].time_released = p.voices[best].age
		p.voices[best].adsr_growl_amp_stage = .Release
		p.voices[best].adsr_growl_puff_stage = .Release
		p.voices[best].adsr_growl_scoop_stage = .Release
	}
}

Growly_Sax_trigger :: proc(p: ^Growly_Sax_Processor, note: u8 = 60, velocity: f32 = 1.0, duration: f32 = 0.0) {
	d := duration
	if d <= 0.0 {
		d = 0.0
		if (p.Amp_attack) + (p.Amp_decay) > d do d = (p.Amp_attack) + (p.Amp_decay)
		if (p.Puff_attack) + (p.Puff_decay) > d do d = (p.Puff_attack) + (p.Puff_decay)
		if (p.Scoop_attack) + (f32(0.200000000)) > d do d = (p.Scoop_attack) + (f32(0.200000000))
		if d <= 0.0 do d = 0.001
	}
	Growly_Sax_note_on(p, note, velocity, d)
}

Growly_Sax_feed_input :: proc(p: ^Growly_Sax_Processor, in_left: f32, in_right: f32) {
	p.ext_in_l = in_left
	p.ext_in_r = in_right
}

Growly_Sax_start :: proc(p: ^Growly_Sax_Processor) {
	p.playing = true
	p.current_step = 0
	p.samples_until_next_step = 0
	p.step_frac_acc = 0.0
}

Growly_Sax_stop :: proc(p: ^Growly_Sax_Processor) {
	p.playing = false
}

Growly_Sax_set_loop :: proc(p: ^Growly_Sax_Processor, loop: bool) {
	p.loop = loop
}

Growly_Sax_is_playing :: proc(p: ^Growly_Sax_Processor) -> bool {
	if p.playing do return true
	for i in 0..<4 {
		if p.voices[i].active do return true
	}
	return false
}

Growly_Sax_set_Air_cutoff :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 20.000000000 do v = 20.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.Air_cutoff = v
}

Growly_Sax_set_Air_resonance :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.100000001 do v = 0.100000001
	if v > 20.000000000 do v = 20.000000000
	p.Air_resonance = v
}

Growly_Sax_set_Amp_attack :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Amp_attack = v
}

Growly_Sax_set_Amp_decay :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Amp_decay = v
}

Growly_Sax_set_Amp_depth :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Amp_depth = v
}

Growly_Sax_set_Amp_release :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Amp_release = v
}

Growly_Sax_set_Amp_sustain :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Amp_sustain = v
}

Growly_Sax_set_Body_cutoff :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 20.000000000 do v = 20.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.Body_cutoff = v
}

Growly_Sax_set_Body_resonance :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.100000001 do v = 0.100000001
	if v > 20.000000000 do v = 20.000000000
	p.Body_resonance = v
}

Growly_Sax_set_Breath_amplitude :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Breath_amplitude = v
}

Growly_Sax_set_Expression_mix :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Expression_mix = v
}

Growly_Sax_set_Formant_cutoff :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 20.000000000 do v = 20.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.Formant_cutoff = v
}

Growly_Sax_set_Formant_resonance :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.100000001 do v = 0.100000001
	if v > 20.000000000 do v = 20.000000000
	p.Formant_resonance = v
}

Growly_Sax_set_Puff_attack :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Puff_attack = v
}

Growly_Sax_set_Puff_decay :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Puff_decay = v
}

Growly_Sax_set_Puff_depth :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Puff_depth = v
}

Growly_Sax_set_Puff_release :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Puff_release = v
}

Growly_Sax_set_Puff_sustain :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Puff_sustain = v
}

Growly_Sax_set_Reed_amplitude :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Reed_amplitude = v
}

Growly_Sax_set_Room_decay :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Room_decay = v
}

Growly_Sax_set_Room_mix :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Room_mix = v
}

Growly_Sax_set_Scoop_attack :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Scoop_attack = v
}

Growly_Sax_set_Scoop_depth :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Scoop_depth = v
}

Growly_Sax_set_Scoop_release :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.001000000 do v = 0.001000000
	if v > 10.000000000 do v = 10.000000000
	p.Scoop_release = v
}

Growly_Sax_set_Scoop_sustain :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.Scoop_sustain = v
}

Growly_Sax_set_Vibrato_amplitude :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.Vibrato_amplitude = v
}

Growly_Sax_set_drive :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 1.000000000 do v = 1.000000000
	if v > 100.000000000 do v = 100.000000000
	p.drive = v
}

Growly_Sax_set_frequency :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.010000000 do v = 0.010000000
	if v > 100.000000000 do v = 100.000000000
	p.frequency = v
}

Growly_Sax_set_outMin :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < -1000000.000000000 do v = -1000000.000000000
	if v > 1000000.000000000 do v = 1000000.000000000
	p.outMin = v
}

Growly_Sax_set_tone :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 100.000000000 do v = 100.000000000
	if v > 20000.000000000 do v = 20000.000000000
	p.tone = v
}

Growly_Sax_set_velocitySensitivity :: proc(p: ^Growly_Sax_Processor, value: f32) {
	v := value
	if v < 0.000000000 do v = 0.000000000
	if v > 1.000000000 do v = 1.000000000
	p.velocitySensitivity = v
}

Growly_Sax_PARAMS := []Skald_Param_Info{
	{"Air_cutoff", 20.000000000, 20000.000000000, 4500.000000000, "Hz"},
	{"Air_resonance", 0.100000001, 20.000000000, 1.000000000, "Q"},
	{"Amp_attack", 0.001000000, 10.000000000, 0.050000001, "s"},
	{"Amp_decay", 0.001000000, 10.000000000, 0.180000007, "s"},
	{"Amp_depth", 0.000000000, 1.000000000, 1.000000000, ""},
	{"Amp_release", 0.001000000, 10.000000000, 0.140000001, "s"},
	{"Amp_sustain", 0.000000000, 1.000000000, 0.800000012, ""},
	{"Body_cutoff", 20.000000000, 20000.000000000, 1600.000000000, "Hz"},
	{"Body_resonance", 0.100000001, 20.000000000, 1.200000048, "Q"},
	{"Breath_amplitude", 0.000000000, 1.000000000, 0.150000006, ""},
	{"Expression_mix", 0.000000000, 1.000000000, 0.250000000, ""},
	{"Formant_cutoff", 20.000000000, 20000.000000000, 1100.000000000, "Hz"},
	{"Formant_resonance", 0.100000001, 20.000000000, 2.500000000, "Q"},
	{"Puff_attack", 0.001000000, 10.000000000, 0.010000000, "s"},
	{"Puff_decay", 0.001000000, 10.000000000, 0.119999997, "s"},
	{"Puff_depth", 0.000000000, 1.000000000, 1.000000000, ""},
	{"Puff_release", 0.001000000, 10.000000000, 0.079999998, "s"},
	{"Puff_sustain", 0.000000000, 1.000000000, 0.250000000, ""},
	{"Reed_amplitude", 0.000000000, 1.000000000, 0.550000012, ""},
	{"Room_decay", 0.001000000, 10.000000000, 1.500000000, "s"},
	{"Room_mix", 0.000000000, 1.000000000, 0.150000006, ""},
	{"Scoop_attack", 0.001000000, 10.000000000, 0.070000000, "s"},
	{"Scoop_depth", 0.000000000, 1.000000000, 1.000000000, ""},
	{"Scoop_release", 0.001000000, 10.000000000, 0.050000001, "s"},
	{"Scoop_sustain", 0.000000000, 1.000000000, 1.000000000, ""},
	{"Vibrato_amplitude", 0.000000000, 20000.000000000, 0.020000000, ""},
	{"drive", 1.000000000, 100.000000000, 18.000000000, "x"},
	{"frequency", 0.010000000, 100.000000000, 5.500000000, "Hz"},
	{"outMin", -1000000.000000000, 1000000.000000000, -0.119999997, ""},
	{"tone", 100.000000000, 20000.000000000, 5000.000000000, "Hz"},
	{"velocitySensitivity", 0.000000000, 1.000000000, 0.800000012, ""},
}

Growly_Sax_set_param :: proc(p: ^Growly_Sax_Processor, name: string, value: f32) -> bool {
	switch name {
	case "Air_cutoff":
		Growly_Sax_set_Air_cutoff(p, value)
		return true
	case "Air_resonance":
		Growly_Sax_set_Air_resonance(p, value)
		return true
	case "Amp_attack":
		Growly_Sax_set_Amp_attack(p, value)
		return true
	case "Amp_decay":
		Growly_Sax_set_Amp_decay(p, value)
		return true
	case "Amp_depth":
		Growly_Sax_set_Amp_depth(p, value)
		return true
	case "Amp_release":
		Growly_Sax_set_Amp_release(p, value)
		return true
	case "Amp_sustain":
		Growly_Sax_set_Amp_sustain(p, value)
		return true
	case "Body_cutoff":
		Growly_Sax_set_Body_cutoff(p, value)
		return true
	case "Body_resonance":
		Growly_Sax_set_Body_resonance(p, value)
		return true
	case "Breath_amplitude":
		Growly_Sax_set_Breath_amplitude(p, value)
		return true
	case "Expression_mix":
		Growly_Sax_set_Expression_mix(p, value)
		return true
	case "Formant_cutoff":
		Growly_Sax_set_Formant_cutoff(p, value)
		return true
	case "Formant_resonance":
		Growly_Sax_set_Formant_resonance(p, value)
		return true
	case "Puff_attack":
		Growly_Sax_set_Puff_attack(p, value)
		return true
	case "Puff_decay":
		Growly_Sax_set_Puff_decay(p, value)
		return true
	case "Puff_depth":
		Growly_Sax_set_Puff_depth(p, value)
		return true
	case "Puff_release":
		Growly_Sax_set_Puff_release(p, value)
		return true
	case "Puff_sustain":
		Growly_Sax_set_Puff_sustain(p, value)
		return true
	case "Reed_amplitude":
		Growly_Sax_set_Reed_amplitude(p, value)
		return true
	case "Room_decay":
		Growly_Sax_set_Room_decay(p, value)
		return true
	case "Room_mix":
		Growly_Sax_set_Room_mix(p, value)
		return true
	case "Scoop_attack":
		Growly_Sax_set_Scoop_attack(p, value)
		return true
	case "Scoop_depth":
		Growly_Sax_set_Scoop_depth(p, value)
		return true
	case "Scoop_release":
		Growly_Sax_set_Scoop_release(p, value)
		return true
	case "Scoop_sustain":
		Growly_Sax_set_Scoop_sustain(p, value)
		return true
	case "Vibrato_amplitude":
		Growly_Sax_set_Vibrato_amplitude(p, value)
		return true
	case "drive":
		Growly_Sax_set_drive(p, value)
		return true
	case "frequency":
		Growly_Sax_set_frequency(p, value)
		return true
	case "outMin":
		Growly_Sax_set_outMin(p, value)
		return true
	case "tone":
		Growly_Sax_set_tone(p, value)
		return true
	case "velocitySensitivity":
		Growly_Sax_set_velocitySensitivity(p, value)
		return true
	}
	return false
}

Growly_Sax_get_param :: proc(p: ^Growly_Sax_Processor, name: string) -> (f32, bool) {
	switch name {
	case "Air_cutoff":
		return p.Air_cutoff, true
	case "Air_resonance":
		return p.Air_resonance, true
	case "Amp_attack":
		return p.Amp_attack, true
	case "Amp_decay":
		return p.Amp_decay, true
	case "Amp_depth":
		return p.Amp_depth, true
	case "Amp_release":
		return p.Amp_release, true
	case "Amp_sustain":
		return p.Amp_sustain, true
	case "Body_cutoff":
		return p.Body_cutoff, true
	case "Body_resonance":
		return p.Body_resonance, true
	case "Breath_amplitude":
		return p.Breath_amplitude, true
	case "Expression_mix":
		return p.Expression_mix, true
	case "Formant_cutoff":
		return p.Formant_cutoff, true
	case "Formant_resonance":
		return p.Formant_resonance, true
	case "Puff_attack":
		return p.Puff_attack, true
	case "Puff_decay":
		return p.Puff_decay, true
	case "Puff_depth":
		return p.Puff_depth, true
	case "Puff_release":
		return p.Puff_release, true
	case "Puff_sustain":
		return p.Puff_sustain, true
	case "Reed_amplitude":
		return p.Reed_amplitude, true
	case "Room_decay":
		return p.Room_decay, true
	case "Room_mix":
		return p.Room_mix, true
	case "Scoop_attack":
		return p.Scoop_attack, true
	case "Scoop_depth":
		return p.Scoop_depth, true
	case "Scoop_release":
		return p.Scoop_release, true
	case "Scoop_sustain":
		return p.Scoop_sustain, true
	case "Vibrato_amplitude":
		return p.Vibrato_amplitude, true
	case "drive":
		return p.drive, true
	case "frequency":
		return p.frequency, true
	case "outMin":
		return p.outMin, true
	case "tone":
		return p.tone, true
	case "velocitySensitivity":
		return p.velocitySensitivity, true
	}
	return 0.0, false
}

Growly_Sax_process :: proc(p: ^Growly_Sax_Processor) -> (f32, f32) {
	sample_rate := p.sample_rate
	output_left: f32 = 0.0
	output_right: f32 = 0.0
	Growly_Sax_process_sequence(p)
	p.total_samples += 1

	node_growl_amp_out_vsum: f32 = 0.0
	for v_idx in 0..<4 {
		voice := &p.voices[v_idx]
		if !voice.active do continue

		voice.age += 1.0 / sample_rate;
		if voice.current_freq != voice.target_freq {
			glide_k := 1.0 / math.max(voice.glide_time * sample_rate, 1.0)
			if glide_k > 1.0 do glide_k = 1.0
			voice.current_freq += (voice.target_freq - voice.current_freq) * glide_k
			if abs(voice.target_freq - voice.current_freq) < 0.1 do voice.current_freq = voice.target_freq
		}
		if voice.age >= voice.duration && voice.duration > 0.0 {
			if voice.adsr_growl_amp_stage != .Release && voice.adsr_growl_amp_stage != .Idle {
				voice.adsr_growl_amp_stage = .Release
				voice.time_released = voice.age
			}
			if voice.adsr_growl_puff_stage != .Release && voice.adsr_growl_puff_stage != .Idle {
				voice.adsr_growl_puff_stage = .Release
				voice.time_released = voice.age
			}
			if voice.adsr_growl_scoop_stage != .Release && voice.adsr_growl_scoop_stage != .Idle {
				voice.adsr_growl_scoop_stage = .Release
				voice.time_released = voice.age
			}
		}
		voice_busy := false
		node_growl_air_out: f32 = 0.0
		node_growl_amp_out: f32 = 0.0
		node_growl_body_out: f32 = 0.0
		node_growl_breath_out: f32 = 0.0
		node_growl_drive_out: f32 = 0.0
		node_growl_formant_out: f32 = 0.0
		node_growl_mixer_out: f32 = 0.0
		node_growl_puff_out: f32 = 0.0
		node_growl_reed_out: f32 = 0.0
		node_growl_scoop_out: f32 = 0.0
		node_growl_scoop_map_out: f32 = 0.0
		node_growl_vibrato_out: f32 = 0.0

		// --- Noise Node growl_breath ---
		{
			white_growl_breath := next_float32(&voice.noise_growl_breath_rng) * 2.0 - 1.0;
			voice.noise_growl_breath_p0 = 0.99765 * voice.noise_growl_breath_p0 + white_growl_breath * 0.0990460;
			voice.noise_growl_breath_p1 = 0.96300 * voice.noise_growl_breath_p1 + white_growl_breath * 0.2965164;
			voice.noise_growl_breath_p2 = 0.57000 * voice.noise_growl_breath_p2 + white_growl_breath * 1.0526913;
			node_growl_breath_out = (voice.noise_growl_breath_p0 + voice.noise_growl_breath_p1 + voice.noise_growl_breath_p2 + white_growl_breath * 0.1848) * 0.25 * (p.Breath_amplitude);
		}

		// --- ADSR Node growl_scoop ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_growl_scoop_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (p.Scoop_attack) > 0 do envelope = voice.age / math.max(f32(p.Scoop_attack), 0.000001); else do envelope = 1.0;
				voice.adsr_growl_scoop_release_level = envelope;
				if voice.age >= (p.Scoop_attack) {
					voice.adsr_growl_scoop_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (p.Scoop_attack);
				if (f32(0.200000000)) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(f32(0.200000000)), 0.000001)) * (1.0 - (p.Scoop_sustain)); else do envelope = (p.Scoop_sustain);
				voice.adsr_growl_scoop_release_level = envelope;
				if time_in_decay >= (f32(0.200000000)) {
					voice.adsr_growl_scoop_stage = .Sustain;
				}
			case .Sustain:
				envelope = (p.Scoop_sustain);
				voice.adsr_growl_scoop_release_level = envelope;
				if envelope <= 0.0001 do voice.adsr_growl_scoop_stage = .Idle;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (p.Scoop_release) > 0 do envelope = voice.adsr_growl_scoop_release_level * (1.0 - (time_in_release / math.max(f32(p.Scoop_release), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_growl_scoop_stage = .Idle;
				}
			}
			vel_scale_growl_scoop: f32 = (1.0 - (f32(0.000000000))) + (f32(0.000000000)) * voice.velocity;
			node_growl_scoop_out = (1.0) * envelope * (p.Scoop_depth) * vel_scale_growl_scoop;
		}

		// --- LFO Node growl_vibrato ---
		voice.lfo_growl_vibrato_phase = math.mod(voice.lfo_growl_vibrato_phase + (2 * f32(math.PI) * (p.frequency) / sample_rate), 2 * f32(math.PI));
		if voice.lfo_growl_vibrato_phase < 0.0 do voice.lfo_growl_vibrato_phase += 2 * f32(math.PI);
		node_growl_vibrato_out = math.sin(voice.lfo_growl_vibrato_phase) * (p.Vibrato_amplitude);

		// --- Filter Node growl_air (SVF) ---
		{
			cutoff_c_growl_air: f32 = math.clamp(f32(p.Air_cutoff), 10.0, sample_rate * 0.16);
			f_growl_air := f32(2.0 * math.sin(f32(math.PI) * cutoff_c_growl_air / sample_rate));
			q_growl_air: f32 = math.clamp(1.0 / math.max(f32(p.Air_resonance), 0.1), 0.05, 1.9 - f_growl_air);
			voice.filter_growl_air_low += f_growl_air * voice.filter_growl_air_band;
			high_growl_air := f32(((node_growl_breath_out)) - voice.filter_growl_air_low - q_growl_air * voice.filter_growl_air_band);
			voice.filter_growl_air_band += f_growl_air * high_growl_air;
			node_growl_air_out = voice.filter_growl_air_band;
		}

		// --- Mapper Node growl_scoop_map ---
		{
			in_range_growl_scoop_map: f32 = f32(f32(1.000000000)) - f32(f32(0.000000000));
			if in_range_growl_scoop_map == 0.0 do in_range_growl_scoop_map = 1.0;
			node_growl_scoop_map_out = math.lerp(f32(p.outMin), f32(f32(0.000000000)), math.clamp((f32((node_growl_scoop_out)) - f32(f32(0.000000000))) / in_range_growl_scoop_map, 0.0, 1.0));
		}

		// --- ADSR Node growl_puff ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_growl_puff_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (p.Puff_attack) > 0 do envelope = voice.age / math.max(f32(p.Puff_attack), 0.000001); else do envelope = 1.0;
				voice.adsr_growl_puff_release_level = envelope;
				if voice.age >= (p.Puff_attack) {
					voice.adsr_growl_puff_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (p.Puff_attack);
				if (p.Puff_decay) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(p.Puff_decay), 0.000001)) * (1.0 - (p.Puff_sustain)); else do envelope = (p.Puff_sustain);
				voice.adsr_growl_puff_release_level = envelope;
				if time_in_decay >= (p.Puff_decay) {
					voice.adsr_growl_puff_stage = .Sustain;
				}
			case .Sustain:
				envelope = (p.Puff_sustain);
				voice.adsr_growl_puff_release_level = envelope;
				if envelope <= 0.0001 do voice.adsr_growl_puff_stage = .Idle;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (p.Puff_release) > 0 do envelope = voice.adsr_growl_puff_release_level * (1.0 - (time_in_release / math.max(f32(p.Puff_release), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_growl_puff_stage = .Idle;
				}
			}
			vel_scale_growl_puff: f32 = (1.0 - (f32(0.500000000))) + (f32(0.500000000)) * voice.velocity;
			node_growl_puff_out = ((node_growl_air_out)) * envelope * (p.Puff_depth) * vel_scale_growl_puff;
		}

		// --- Oscillator Node growl_reed (Unison/Detune) ---
		{
			unison_out: f32 = 0.0;
			unison_count := 1;
			for i in 0..<unison_count {
				detune_amount: f32 = 0.0;
				if unison_count > 1 do detune_amount = (f32(i) / (f32(unison_count) - 1.0) - 0.5) * 2.0 * (0.000000000);
				detuned_freq: f32 = ((voice.current_freq) * math.pow(2.0, math.clamp(f32(node_growl_scoop_map_out + node_growl_vibrato_out), -10.0, 10.0))) * math.pow(2.0, detune_amount / 1200.0);
				phase_rads: f32 = f32(f32(0.000000000)) * (f32(math.PI) / 180.0);
				voice.osc_growl_reed_phase[i] = math.mod(voice.osc_growl_reed_phase[i] + (2 * f32(math.PI) * detuned_freq / sample_rate), 2 * f32(math.PI));
				final_phase := math.mod(voice.osc_growl_reed_phase[i] + phase_rads, 2 * f32(math.PI));
				unison_out += ((final_phase / f32(math.PI)) - 1.0);
			}
			if unison_count > 0 do node_growl_reed_out = (unison_out / f32(unison_count)) * (p.Reed_amplitude);
		}

		// --- Filter Node growl_body (SVF) ---
		{
			cutoff_c_growl_body: f32 = math.clamp(f32(p.Body_cutoff), 10.0, sample_rate * 0.16);
			f_growl_body := f32(2.0 * math.sin(f32(math.PI) * cutoff_c_growl_body / sample_rate));
			q_growl_body: f32 = math.clamp(1.0 / math.max(f32(p.Body_resonance), 0.1), 0.05, 1.9 - f_growl_body);
			voice.filter_growl_body_low += f_growl_body * voice.filter_growl_body_band;
			high_growl_body := f32(((node_growl_reed_out)) - voice.filter_growl_body_low - q_growl_body * voice.filter_growl_body_band);
			voice.filter_growl_body_band += f_growl_body * high_growl_body;
			node_growl_body_out = voice.filter_growl_body_low;
		}

		// --- Filter Node growl_formant (SVF) ---
		{
			cutoff_c_growl_formant: f32 = math.clamp(f32(p.Formant_cutoff), 10.0, sample_rate * 0.16);
			f_growl_formant := f32(2.0 * math.sin(f32(math.PI) * cutoff_c_growl_formant / sample_rate));
			q_growl_formant: f32 = math.clamp(1.0 / math.max(f32(p.Formant_resonance), 0.1), 0.05, 1.9 - f_growl_formant);
			voice.filter_growl_formant_low += f_growl_formant * voice.filter_growl_formant_band;
			high_growl_formant := f32(((node_growl_reed_out)) - voice.filter_growl_formant_low - q_growl_formant * voice.filter_growl_formant_band);
			voice.filter_growl_formant_band += f_growl_formant * high_growl_formant;
			node_growl_formant_out = voice.filter_growl_formant_band;
		}

		// --- Mixer Node growl_mixer (3 inputs) ---
		{
			mix_sum_growl_mixer: f32 = 0.0;
			mix_sum_growl_mixer += node_growl_body_out * (f32(0.800000012));
			mix_sum_growl_mixer += node_growl_formant_out * (f32(0.500000000));
			mix_sum_growl_mixer += node_growl_puff_out * (f32(0.349999994));
		node_growl_mixer_out = mix_sum_growl_mixer;
		}

		// --- Distortion Node growl_drive (soft) ---
		{
			dist_in_growl_drive: f32 = ((node_growl_mixer_out));
			dist_k_growl_drive: f32 = math.max(f32(p.drive), 1.0);
			dist_wet_growl_drive: f32 = math.tanh(dist_in_growl_drive * dist_k_growl_drive);
			tone_k_growl_drive: f32 = math.clamp(2.0 * f32(math.PI) * math.clamp(f32(p.tone), 100.0, 20000.0) / sample_rate, 0.001, 1.0);
			voice.dist_growl_drive_tone += tone_k_growl_drive * (dist_wet_growl_drive - voice.dist_growl_drive_tone);
			mix_growl_drive: f32 = math.clamp(f32(p.Expression_mix), 0.0, 1.0);
			node_growl_drive_out = dist_in_growl_drive * (1.0 - mix_growl_drive) + voice.dist_growl_drive_tone * mix_growl_drive;
		}

		// --- ADSR Node growl_amp ---
		{
			envelope: f32 = 0.0;
			switch voice.adsr_growl_amp_stage {
			case .Idle:
				envelope = 0.0;
			case .Attack:
				if (p.Amp_attack) > 0 do envelope = voice.age / math.max(f32(p.Amp_attack), 0.000001); else do envelope = 1.0;
				voice.adsr_growl_amp_release_level = envelope;
				if voice.age >= (p.Amp_attack) {
					voice.adsr_growl_amp_stage = .Decay;
				}
			case .Decay:
				time_in_decay := voice.age - (p.Amp_attack);
				if (p.Amp_decay) > 0 do envelope = 1.0 - (time_in_decay / math.max(f32(p.Amp_decay), 0.000001)) * (1.0 - (p.Amp_sustain)); else do envelope = (p.Amp_sustain);
				voice.adsr_growl_amp_release_level = envelope;
				if time_in_decay >= (p.Amp_decay) {
					voice.adsr_growl_amp_stage = .Sustain;
				}
			case .Sustain:
				envelope = (p.Amp_sustain);
				voice.adsr_growl_amp_release_level = envelope;
				if envelope <= 0.0001 do voice.adsr_growl_amp_stage = .Idle;
			case .Release:
				time_in_release := voice.age - voice.time_released;
				if (p.Amp_release) > 0 do envelope = voice.adsr_growl_amp_release_level * (1.0 - (time_in_release / math.max(f32(p.Amp_release), 0.000001))); else do envelope = 0.0;
				if envelope <= 0 {
					envelope = 0;
					voice.adsr_growl_amp_stage = .Idle;
				}
			}
			vel_scale_growl_amp: f32 = (1.0 - (p.velocitySensitivity)) + (p.velocitySensitivity) * voice.velocity;
			node_growl_amp_out = ((node_growl_drive_out)) * envelope * (p.Amp_depth) * vel_scale_growl_amp;
		}

		node_growl_amp_out_vsum += node_growl_amp_out
		if voice.adsr_growl_amp_stage != .Idle do voice_busy = true
		if voice.adsr_growl_puff_stage != .Idle do voice_busy = true
		if voice.adsr_growl_scoop_stage != .Idle do voice_busy = true
		if !voice_busy do voice.active = false
	}

	// --- Bus effects (once per sample, post voice sum) ---
	{
		node_growl_amp_out := node_growl_amp_out_vsum
		node_growl_reverb_out: f32 = 0.0
		// --- Reverb Node growl_reverb (Simple FDN) ---
		{
			delay_samples_growl_reverb := int(math.clamp((0.075000000) * sample_rate, 0, 96000-1));
			read_index_growl_reverb := (p.delay_growl_reverb_write_index - delay_samples_growl_reverb + len(p.delay_growl_reverb_buffer)) % len(p.delay_growl_reverb_buffer);
			delayed_sample_growl_reverb := p.delay_growl_reverb_buffer[read_index_growl_reverb];
			decay_gain_growl_reverb: f32 = math.clamp(math.pow(f32(0.001), f32(0.075) / math.max(f32(p.Room_decay), 0.01)), 0.0, 0.95);
			p.delay_growl_reverb_buffer[p.delay_growl_reverb_write_index] = ((node_growl_amp_out)) + delayed_sample_growl_reverb * decay_gain_growl_reverb;
			p.delay_growl_reverb_write_index = (p.delay_growl_reverb_write_index + 1) % len(p.delay_growl_reverb_buffer);
			node_growl_reverb_out = ((node_growl_amp_out)) * (1.0 - (p.Room_mix)) + delayed_sample_growl_reverb * (p.Room_mix);
		}

		output_left += node_growl_reverb_out
		output_right += node_growl_reverb_out
	}
	return output_left * f32(0.660000026), output_right * f32(0.660000026)
}
Growly_Sax_process_sequence :: proc(p: ^Growly_Sax_Processor) {
	if !p.playing do return
	samples_per_step_f := p.sample_rate * 60.0 / (p.bpm * 4.0)
	if p.samples_until_next_step == 0 {
		// Track "Growly Sax" (16 steps)
		switch p.current_step % 16 {
		case 0:
			Growly_Sax_note_on(p, 60, 1.000000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 2:
			Growly_Sax_note_on(p, 60, 1.000000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 4:
			Growly_Sax_note_on(p, 60, 1.000000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 10:
			Growly_Sax_note_on(p, 60, 1.000000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		case 13:
			Growly_Sax_note_on(p, 60, 1.000000000, f32(1.000000000) * (60.0 / p.bpm / 4.0))
		}
		p.current_step += 1
		if p.current_step >= 16 {
			if p.loop {
				p.current_step = 0
			} else {
				p.playing = false
			}
		}
		p.step_frac_acc += samples_per_step_f
		n_step := u64(math.max(p.step_frac_acc, 1.0))
		p.step_frac_acc -= f32(n_step)
		p.samples_until_next_step = n_step - 1
	} else {
		p.samples_until_next_step -= 1
	}
}

// --- Project Wrapper (test-harness convenience) ---
Project_State :: struct {
	GW_Hat_Static: ^GW_Hat_Static_Processor,
	GW_Grunt_Swarm_Bass: ^GW_Grunt_Swarm_Bass_Processor,
	GW_Splitter_Echo_Stab: ^GW_Splitter_Echo_Stab_Processor,
	Tuba: ^Tuba_Processor,
	Growly_Sax: ^Growly_Sax_Processor,
}

project_init :: proc(p: ^Project_State, sr: f32) {
	p.GW_Hat_Static = new(GW_Hat_Static_Processor)
	GW_Hat_Static_init(p.GW_Hat_Static, sr)
	GW_Hat_Static_start(p.GW_Hat_Static)
	p.GW_Grunt_Swarm_Bass = new(GW_Grunt_Swarm_Bass_Processor)
	GW_Grunt_Swarm_Bass_init(p.GW_Grunt_Swarm_Bass, sr)
	GW_Grunt_Swarm_Bass_start(p.GW_Grunt_Swarm_Bass)
	p.GW_Splitter_Echo_Stab = new(GW_Splitter_Echo_Stab_Processor)
	GW_Splitter_Echo_Stab_init(p.GW_Splitter_Echo_Stab, sr)
	GW_Splitter_Echo_Stab_start(p.GW_Splitter_Echo_Stab)
	p.Tuba = new(Tuba_Processor)
	Tuba_init(p.Tuba, sr)
	Tuba_start(p.Tuba)
	p.Growly_Sax = new(Growly_Sax_Processor)
	Growly_Sax_init(p.Growly_Sax, sr)
	Growly_Sax_start(p.Growly_Sax)
}

project_process :: proc(p: ^Project_State) -> (f32, f32) {
	mixed_left: f32 = 0.0
	mixed_right: f32 = 0.0
	{ l, r := GW_Hat_Static_process(p.GW_Hat_Static); mixed_left += l; mixed_right += r }
	{ l, r := GW_Grunt_Swarm_Bass_process(p.GW_Grunt_Swarm_Bass); mixed_left += l; mixed_right += r }
	{ l, r := GW_Splitter_Echo_Stab_process(p.GW_Splitter_Echo_Stab); mixed_left += l; mixed_right += r }
	{ l, r := Tuba_process(p.Tuba); mixed_left += l; mixed_right += r }
	{ l, r := Growly_Sax_process(p.Growly_Sax); mixed_left += l; mixed_right += r }
	mixed_left = math.tanh(mixed_left * 0.750000000)
	mixed_right = math.tanh(mixed_right * 0.750000000)
	return mixed_left, mixed_right
}

project_destroy :: proc(p: ^Project_State) {
	free(p.GW_Hat_Static)
	free(p.GW_Grunt_Swarm_Bass)
	free(p.GW_Splitter_Echo_Stab)
	free(p.Tuba)
	free(p.Growly_Sax)
}
